import {
  Award,
  BarChart3,
  Clock,
  Globe,
  Handshake,
  Heart,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  MessageCircle,
  Rocket,
  Search,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  UserCheck,
  Wrench,
  Zap,
} from 'lucide-react'

export const iconMap = {
  userCheck: UserCheck,
  layers: Layers,
  shield: Shield,
  zap: Zap,
  heart: Heart,
  target: Target,
  rocket: Rocket,
  lightbulb: Lightbulb,
  handshake: Handshake,
  lock: Lock,
  globe: Globe,
  barChart: BarChart3,
  messageCircle: MessageCircle,
  clock: Clock,
  leaf: Leaf,
  award: Award,
  wrench: Wrench,
  search: Search,
  trendingUp: TrendingUp,
  sparkles: Sparkles,
}

export const iconOptions = [
  { label: 'Utilisateur ✓', value: 'userCheck' },
  { label: 'Calques / vision 360°', value: 'layers' },
  { label: 'Bouclier', value: 'shield' },
  { label: 'Éclair', value: 'zap' },
  { label: 'Cœur', value: 'heart' },
  { label: 'Cible', value: 'target' },
  { label: 'Fusée', value: 'rocket' },
  { label: 'Ampoule', value: 'lightbulb' },
  { label: 'Poignée de main', value: 'handshake' },
  { label: 'Cadenas', value: 'lock' },
  { label: 'Globe', value: 'globe' },
  { label: 'Graphique', value: 'barChart' },
  { label: 'Bulle de discussion', value: 'messageCircle' },
  { label: 'Horloge', value: 'clock' },
  { label: 'Feuille / sobriété', value: 'leaf' },
  { label: 'Récompense', value: 'award' },
  { label: 'Clé à molette', value: 'wrench' },
  { label: 'Loupe', value: 'search' },
  { label: 'Courbe de croissance', value: 'trendingUp' },
  { label: 'Étincelles', value: 'sparkles' },
]
