import type { CollectionConfig } from 'payload'
import { publicRead, editorOrAdmin, adminOnly } from '../access'

export const CaseStudies: CollectionConfig = {
  slug: 'case-studies',
  labels: { singular: 'Étude de cas', plural: 'Études de cas' },
  admin: {
    useAsTitle: 'client_name',
    defaultColumns: ['client_name', 'industry', 'is_featured', 'updatedAt'],
    group: 'Contenu',
  },
  access: {
    read: publicRead,
    create: editorOrAdmin,
    update: editorOrAdmin,
    delete: adminOnly,
  },
  fields: [
    { name: 'client_name', type: 'text', required: true, label: 'Nom du client' },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      label: 'Slug (URL)',
      admin: { position: 'sidebar' },
    },
    { name: 'excerpt', type: 'textarea', label: 'Résumé court' },
    { name: 'excerpt_en', type: 'textarea', label: 'Résumé court (EN)' },
    {
      name: 'industry',
      type: 'select',
      label: 'Secteur',
      options: [
        { label: 'E-commerce', value: 'ecommerce' },
        { label: 'Services', value: 'services' },
        { label: 'Industrie', value: 'industry' },
        { label: 'Santé', value: 'health' },
        { label: 'Éducation', value: 'education' },
        { label: 'Immobilier', value: 'real-estate' },
        { label: 'Restauration', value: 'restaurant' },
        { label: 'Autre', value: 'other' },
      ],
    },
    {
      name: 'category',
      type: 'select',
      label: 'Type de projet',
      options: [
        { label: 'Site vitrine', value: 'showcase' },
        { label: 'E-commerce', value: 'ecommerce' },
        { label: 'Application web', value: 'webapp' },
        { label: 'SEO', value: 'seo' },
        { label: 'Automation', value: 'automation' },
      ],
    },
    { name: 'image', type: 'upload', relationTo: 'media', label: 'Image principale' },
    { name: 'logo', type: 'upload', relationTo: 'media', label: 'Logo du client' },
    { name: 'challenge', type: 'richText', label: 'Défi / Problématique' },
    { name: 'challenge_en', type: 'richText', label: 'Défi (EN)' },
    { name: 'solution', type: 'richText', label: 'Solution apportée' },
    { name: 'solution_en', type: 'richText', label: 'Solution (EN)' },
    { name: 'results', type: 'richText', label: 'Résultats obtenus' },
    { name: 'results_en', type: 'richText', label: 'Résultats (EN)' },
    {
      name: 'metrics',
      type: 'array',
      label: 'Métriques clés',
      fields: [
        { name: 'label', type: 'text', required: true },
        { name: 'value', type: 'text', required: true },
      ],
    },
    {
      name: 'technologies',
      type: 'array',
      label: 'Technologies utilisées',
      fields: [{ name: 'name', type: 'text', required: true }],
    },
    {
      name: 'services_used',
      type: 'relationship',
      relationTo: 'services',
      hasMany: true,
      label: 'Services utilisés',
    },
    { name: 'duration', type: 'text', label: 'Durée du projet' },
    { name: 'team_size', type: 'number', label: "Taille de l'équipe" },
    { name: 'testimonial', type: 'textarea', label: 'Témoignage client' },
    { name: 'testimonial_en', type: 'textarea', label: 'Témoignage client (EN)' },
    { name: 'testimonial_author', type: 'text', label: 'Auteur du témoignage' },
    {
      name: 'is_featured',
      type: 'checkbox',
      defaultValue: false,
      label: 'Mis en avant',
      admin: { position: 'sidebar' },
    },
    {
      name: 'seo',
      type: 'group',
      label: 'SEO',
      fields: [
        { name: 'metaTitle', type: 'text', label: 'Titre SEO' },
        { name: 'metaDescription', type: 'textarea', label: 'Description SEO' },
      ],
    },
  ],
}
